<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Terminal.Gui" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Harness.Host" />
    <InternalsVisibleTo Include="Harness.Presentation.Terminal.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Harness.BusinessLogic/Harness.BusinessLogic.csproj" />
  </ItemGroup>
</Project>
