<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Ace4896.DBus.Services.Secrets" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="LibGit2Sharp" />
    <PackageReference Include="dbup-core" />
    <PackageReference Include="dbup-sqlite" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Features" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.SqliteVec" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <PackageReference Include="Tmds.DBus.Generator" PrivateAssets="all" />
    <PackageReference Include="Tmds.DBus.Protocol" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Harness.BusinessLogic.Tests" />
    <InternalsVisibleTo Include="Harness.DataAccess.Tests" />
    <InternalsVisibleTo Include="Harness.Host" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence/Migrations/*.sql" />
    <AdditionalFiles Include="VisualCapture/Dbus/org.freedesktop.portal.Request.xml"
                     Namespace="Harness.DataAccess.VisualCapture.DBus"
                     GenerateDBusTypes="true" />
    <AdditionalFiles Include="VisualCapture/Dbus/org.freedesktop.portal.Screenshot.xml"
                     Namespace="Harness.DataAccess.VisualCapture.DBus"
                     GenerateDBusTypes="true" />
  </ItemGroup>
</Project>
