<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Ace4896.DBus.Services.Secrets" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="LibGit2Sharp" />
    <PackageReference Include="dbup-core" />
    <PackageReference Include="dbup-sqlite" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Harness.DataAccess.Tests" />
    <InternalsVisibleTo Include="Harness.Host" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence/Migrations/*.sql" />
  </ItemGroup>
</Project>
