<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Harness.UI.Avalonia.Tests" />
  </ItemGroup>
</Project>
